monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - external_api
        - product_import
        - messenger
    handlers:
#        file_log: # not working due to docker file permissions issues
#            channels: [ 'external_api' ]
#            type: rotating_file
#            max_files: 10
#            # log to var/log/(environment).log
#            path: "%kernel.logs_dir%/external_api/%kernel.environment%.log"
#            # log *all* messages (debug is lowest level)
#            level: debug
        db_log:
            type: service
            id: App\Log\Monolog\DatabaseHandler
            channels: [ 'external_api', 'product_import', 'messenger' ]
            level: debug
